models/Loan.php
<?php


namespace app\models;

use yii\db\ActiveRecord;


/**
 * Loan model
 *
 * @property integer $id
 * @property integer $loan_duration
 * @property string $start_date
 * @property integer $loan_amount
 * @property integer $annual_interest_rate
 *
 */
class Loan extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'loans';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['start_date', 'loan_duration', 'loan_amount', 'annual_interest_rate'], 'required', 'message'=>'Поле <{attribute}> не может быть пустым.'],
            [['start_date', 'loan_duration', 'loan_amount', 'annual_interest_rate'], 'filter', 'filter' => 'trim'],
            [['loan_duration', 'loan_amount', 'annual_interest_rate'], 'integer', 'message'=>'Поле <{attribute}> должно быть числом.'],
            [['start_date'], 'string']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'start_date' => 'Начальная дата',
            'loan_duration' => 'Срок займа (в месяцах)',
            'loan_amount' => 'Сумма займа',
            'annual_interest_rate' => 'Годовая процентная ставка'
        ];
    }

}

models/Payments.php
<?php


namespace app\models;


use yii\db\ActiveRecord;

/**
 * Payments model
 *
 * @property integer $id
 * @property integer $loan_id
 * @property integer $payment_number
 * @property string $payment_date
 * @property integer $payment_amount
 * @property integer $interest_amount
 * @property integer $main_sum_amount
 * @property integer $remaining_loan
 *
 */

class Payments extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'payments';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['loan_id', 'payment_number', 'payment_date', 'payment_amount', 'interest_amount', 'main_sum_amount', 'remaining_loan'], 'required', 'message'=>'Поле <{attribute}> не может быть пустым.'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'payment_number' => 'Номер платежа',
            'payment_date' => 'Дата платежа',
            'payment_amount' => 'Общая сумма платежа',
            'interest_amount' => 'Сумма погашаемых процентов',
            'main_sum_amount' => 'Сумма погашаемого основного долга',
            'remaining_loan' => 'Остаток основного долга'
        ];
    }

    public static function CalculatePayments(Loan $Loan)
    {
        $monthly_interest_rate = $Loan->annual_interest_rate / 100 / 12;
        $payment_amount = $Loan->loan_amount * ($monthly_interest_rate + $monthly_interest_rate / ((1 + $monthly_interest_rate) ** $Loan->loan_duration - 1));
        $remaining_loan = $Loan->loan_amount;
        for ($i = 1; $i <= $Loan->loan_duration; $i++) {
            $interest_amount = $remaining_loan * $monthly_interest_rate;
            $main_payment = $payment_amount - $interest_amount;
            $remaining_loan -= $main_payment;
            $payment_date = date('Y-m-d', strtotime("+$i months", strtotime($Loan->start_date)));
            $Payments = new Payments();
            $Payments->payment_amount = round($payment_amount);
            $Payments->interest_amount =  round($interest_amount);
            $Payments->main_sum_amount =  round($main_payment);
            $Payments->remaining_loan =  round($remaining_loan);
            $Payments->payment_date =  $payment_date;
            $Payments->payment_number = $i;
            $Payments->loan_id = $Loan->id;
            $Payments->save();
        }
    }
}

models/User.php
<?php

namespace app\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Loan;
use app\models\Payments;
use Yii;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\web\Controller;



class SiteController extends Controller
{

    /**
     *
     * @return string
     */
    public function actionIndex()
    {
        $Loan = new Loan();
        if(Yii::$app->request->isPost && $Loan->load(Yii::$app->request->post())){
            $Loan->save();
            Payments::CalculatePayments($Loan);
            return $this->redirect(Url::toRoute(['site/payments', 'id' => $Loan->id]));
        }
        return $this->render('index', ['model' => $Loan]);
    }

    public function actionLoans(){
        $data_provider = new ActiveDataProvider([
           'query' => Loan::find()
        ]);
        return $this->render('loan', ['data_provider' => $data_provider]);
    }

    public function actionPayments($id){
        $data_provider = new ActiveDataProvider([
            'query' => Payments::find()
                ->where(['loan_id' => $id])
                ->orderBy(['payment_number' => SORT_ASC])
        ]);
        return $this->render('payments', ['data_provider' => $data_provider]);
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Главная', 'url' => ['/site/index']],
            ['label' => 'Таблица заемов', 'url' => ['/site/loans']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\jui\DatePicker;

?>
<div class="site-index">
    <h2 class="text-center">Калькулятор графика расчета аннуитетных платежей</h2>
    <hr>
    <div class="row">
        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'start_date')->widget(DatePicker::class, [
            'language' => 'ru',
            'dateFormat' => 'yyyy-MM-dd',
            'options' => ['class' => 'form-control']
        ]) ?>


        <?= $form->field($model, 'loan_amount')->textInput()?>

        <?= $form->field($model, 'loan_duration')->textInput() ?>

        <?= $form->field($model, 'annual_interest_rate')->textInput() ?>

        <div class="form-group">
            <?= Html::submitButton('Рассчитать', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>

</div>

views/site/loan.php
<?php

/* @var $this yii\web\View */
/* @var $data_provider ActiveDataProvider */

$this->title = 'Таблица займов';


use yii\data\ActiveDataProvider;
use yii\grid\GridView; ?>

<div class="site-index">
    <h2 class="text-center">Таблица займов</h2>
    <hr>
    <div class="row">
        <?= GridView::widget([
            'dataProvider' => $data_provider,
            'columns' => [
                'start_date',
                'loan_amount',
                'loan_duration',
                'annual_interest_rate',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{payments}',
                    'buttons' => [
                        'payments' => function ($url, $model) {
                            return \yii\helpers\Html::a('График платежей', \yii\helpers\Url::toRoute(['site/payments', 'id' => $model->id]), ['class' => 'btn btn-default']);
                        }
                    ]
                ],
            ]
        ]); ?>
    </div>

</div>

views/site/payments.php
<?php

/* @var $this yii\web\View */
/* @var $data_provider ActiveDataProvider */

$this->title = 'Таблица платежей';


use yii\data\ActiveDataProvider;
use yii\grid\GridView; ?>

<div class="site-index">
    <h2 class="text-center">Таблица платежей</h2>
    <hr>
    <div class="row">
        <?= GridView::widget([
            'dataProvider' => $data_provider,
            'columns' => [
                'payment_number',
                'payment_date',
                'payment_amount',
                'interest_amount',
                'main_sum_amount',
                'remaining_loan'
            ]
        ]); ?>
    </div>

</div>